name: Test Badges & Splash Screen (develop)
author: bertpluymers
description: Generate version-specific images displayed in readme file & upload to appropriate folder on GH pages

inputs:
    uv_version:
        required: true
        description: "Version of UV to be used."
    github_token:
        required: true
        description: "Github token to be used to upload to github pages."


runs:
    using: "composite"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop  # this always acts upon the develop branch

      - name: Determine Package version
        shell: bash
        run: |
            PACKAGE_VERSION=$(uv version --short)
            echo "PACAKGE_EFFECTIVE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ inputs.uv_version }}

      - name: Create coverage report
        shell: bash
        run: |
            uv venv
            source .venv/bin/activate
            uv sync
            uv run --python 3.10 pytest ./tests --junitxml=junit.xml --cov=./snuffled/ --cov-report=xml
            uv run --python 3.13 --all-extras pytest ./tests --junitxml=junit.xml --cov=./snuffled/ --cov-append --cov-report=xml

      - name: Generate badges
        shell: bash
        run: |            
            PACKAGE_VERSION="$(uv version --short)"
            uv run genbadge tests -i junit.xml -o "./pages/version_artifacts/v${PACKAGE_EFFECTIVE_VERSION}/badge-tests.svg"
            uv run genbadge coverage -i coverage.xml -o "./pages/version_artifacts/v${PACKAGE_EFFECTIVE_VERSION}/badge-coverage.svg"

      - name: Prepare splash screen
        shell: bash
        run: cp "./images/splash.webp" "./pages/version_artifacts/v${PACKAGE_EFFECTIVE_VERSION}/splash.webp"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Create Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ inputs.github_token }}
          publish_dir: './pages'
          publish_branch: 'gh-pages'
          keep_files: true

      - name: Update README URLs
        shell: bash
        run: |
          uv run --python 3.13 .github/scripts/update_readme_urls.py "$GITHUB_WORKSPACE/.python-versions" "$GITHUB_WORKSPACE/pyproject.toml" "$GITHUB_WORKSPACE/README.md"
          echo "----------------------------------------------------------"
          cat "$GITHUB_WORKSPACE/README.md" | head -n 10
          echo "..."
          echo "----------------------------------------------------------"

      - name: Commit changes
        shell: bash
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email ""          
          git diff --quiet || (git add "$GITHUB_WORKSPACE/README.md" && git commit -m "Update README.md image URLs")          
          git push