name: Publish to PROD (pypi.org)
author: bertpluymers
description: Build package & publish to pypi.org

inputs:
    uv_version:
        required: true
        description: "Version of UV to be used."

runs:
    using: "composite"
    steps:

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ inputs.uv_version }}

      - name: Build package with uv
        shell: bash
        run: uv build

      - name: Publish package distributions to PyPI   [---PROD---]
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
