name: Publish to DEV (test.pypi.org)
author: bertpluymers
description: Build package with a dev version & publish to test.pypi.org

inputs:
    uv_version:
        required: true
        description: "Version of UV to be used."
    dev_version:
        required: true
        description: "Number to be appended as .dev<nr> to package version"

runs:
    using: "composite"
    steps:

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ inputs.uv_version }}

      - name: Update version in pyproject.toml
        shell: bash
        run: |
          ver_dev="$(uv version --short).dev${{ inputs.dev_version }}"
          echo "Updating version to ${ver_dev}"
          uv version "${ver_dev}"

      - name: Build package with uv
        shell: bash
        run: uv build

      - name: Publish package distributions to PyPI   [---DEV---]
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
