name: Update Splash Image
author: Bert Pluymers
description: Generate updated Splash image with appropriate package version

inputs:
    uv_version:
        required: true
        description: "Version of UV to be used."
    github_token:
        required: true
        description: "Github token to be used to upload to github pages"


runs:
    using: "composite"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: '${{ inputs.github_token }}'
          ref: develop  # this always acts upon the develop branch

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ inputs.uv_version }}

      - name: Determine Package version
        shell: bash
        run: |
            PACKAGE_VERSION=$(uv version --short)
            echo "PACKAGE_EFFECTIVE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV            

      - name: Install ImageMagick 7
        uses: mfinelli/setup-imagemagick@v7

      - name: Prepare splash screen
        shell: bash
        run: |
            magick -pointsize 76 -background transparent \
                   -font "./images/splash/google_fonts_montserrat_bold.ttf" -fill "#ffffff" label:"S" \
                   -font "./images/splash/google_fonts_montserrat_regular.ttf" -fill "#bbbbbb" label:"ystematic " \
                   -font "./images/splash/google_fonts_montserrat_bold.ttf" -fill "#ffffff" label:"N" \
                   -font "./images/splash/google_fonts_montserrat_regular.ttf" -fill "#bbbbbb" label:"umerical " \
                   -font "./images/splash/google_fonts_montserrat_bold.ttf" -fill "#ffffff" label:"U" \
                   -font "./images/splash/google_fonts_montserrat_regular.ttf" -fill "#bbbbbb" label:"nivariate " \
                   -font "./images/splash/google_fonts_montserrat_bold.ttf" -fill "#ffffff" label:"F" \
                   -font "./images/splash/google_fonts_montserrat_regular.ttf" -fill "#bbbbbb" label:"ull-" \
                   -font "./images/splash/google_fonts_montserrat_bold.ttf" -fill "#ffffff" label:"F" \
                   -font "./images/splash/google_fonts_montserrat_regular.ttf" -fill "#bbbbbb" label:"unction ana" \
                   -font "./images/splash/google_fonts_montserrat_bold.ttf" -fill "#ffffff" label:"L" \
                   -font "./images/splash/google_fonts_montserrat_regular.ttf" -fill "#bbbbbb" label:"ysis for " \
                   -font "./images/splash/google_fonts_montserrat_bold.ttf" -fill "#ffffff" label:"E" \
                   -font "./images/splash/google_fonts_montserrat_regular.ttf" -fill "#bbbbbb" label:"stablishing " \
                   -font "./images/splash/google_fonts_montserrat_bold.ttf" -fill "#ffffff" label:"D" \
                   -font "./images/splash/google_fonts_montserrat_regular.ttf" -fill "#bbbbbb" label:"ifficulty of root-finding" \
                   +append "./images/header.png"
            magick "./images/splash/splash.webp" "./images/header.png" -gravity North -geometry +0+5 -composite "./images/temp.png"
            magick -pointsize 30 -font "./images/splash/google_fonts_montserrat_italic.ttf" "./images/temp.png" -gravity SouthWest -fill "#ffffff" -annotate +10+5 "DiffusionBee 2.5.3 (FLUX.1-dev + Real-ESRGAN)" "./images/temp.png"
            magick -pointsize 100 -font "./images/splash/google_fonts_montserrat_bold.ttf" "./images/temp.png" -gravity West -fill "black" -annotate +2793+273 "v${PACKAGE_EFFECTIVE_VERSION}" "./images/temp.png"            
            magick -pointsize 100 -font "./images/splash/google_fonts_montserrat_bold.ttf" "./images/temp.png" -gravity West -fill "white" -annotate +2790+270 "v${PACKAGE_EFFECTIVE_VERSION}" -quality 90 -define webp:lossless=false "./images/splash_with_version.webp"                                                
            mkdir -p "./splash/"
            cp "./images/splash_with_version.webp" "./splash/splash.webp"

      - name: Pass splash to next action
        uses: actions/upload-artifact@v4
        with:
          name: splash
          path: ./splash/